### ISSUE TITLE
War loss of 0 is automatically set to 1

### ISSUE THREAD

**Issue by Westo48** [MagicTheDev/MagicBot#37]
https://github.com/MagicTheDev/MagicBot/blob/7f2bd517593467800ef5c16a2a52ab8f6c47d78c/Clan/ClanResponder.py#L39

@MagicTheDev, it seems as though when a clan's war loss is 0 you have it changed to a war loss of one.

Seems like an easy fix, but I figured I would check, why is this?

**Comment by Westo48** [comment]
In that case, should you handle the error where it happens rather than hardcoding incorrect values?

**Comment by MagicTheDev** [comment]
Ratio requires a valid number to divided by, it should just be a separate variable or different ratio calculation if it errors

**Comment by Westo48** [comment]
Gotcha, my personal suggestion for this would be to update the logic where the calculation happens (same logic really, if it is 0, then calculate it a different way). I don't think this has a need to raise an error tbh, just `if x=0` should be more than sufficient where the ratio calculation happens.

You may not even have to change the value if you're calculating a ratio. A potential fix could be
```py
if war_loss==0:
    win_ratio=war_wins
```
simply because war_wins/1=>war_wins, so why not just set it to war wins to begin with. That way there is no need to change any values or anything like that.

Thoughts?

**Comment by Westo48** [comment]
Sidenote:

> `war_wins / 1 = war_wins`

This also will work when war_wins = 0 -> `0 / 1 = 0`

**Comment by MagicTheDev** [comment]
Yes that would be the best way
